name: Publish development

on:
  workflow_dispatch:
  push:
    branches:
#    - 'main'
    - '**'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build.outputs.artifact_name }}
        path: ${{ github.workspace }}

    - uses: vimtor/action-zip@v1
      with:
        files: ${{ needs.build.outputs.artifact_name }}
        dest: SixDash-latest.zip

    - name: Update release
      uses: IsaacShelton/update-existing-release@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./SixDash-latest.zip
        release: Development
        prerelease: true
